from __future__ import annotations

import shutil
from pathlib import Path

import click

from ._version import __version__
from .codegen import generate_source, generate_tree
from .compiler import compile_fdset

_GENERATED_MARKER = "Generated by protodantic"


@click.group(context_settings={"help_option_names": ["-h", "--help"]})
@click.version_option(__version__, prog_name="protodantic")
def main() -> None:
    """Bidirectional bridge between Protocol Buffers and pydantic models."""


@main.command()
@click.argument("protos", nargs=-1, required=True)
@click.option(
    "-I", "--include", "includes", multiple=True, metavar="DIR",
    help="Additional import search path (repeatable).",
)
@click.option(
    "-o", "--out", "out", required=True, metavar="PATH",
    help="Output: a .py module file, or a package directory for tree layout.",
)
@click.option(
    "--layout", type=click.Choice(["module", "tree"]), default=None,
    help="Override the input-shape default (files -> module, directory -> tree).",
)
def generate(protos: tuple[str, ...], includes: tuple[str, ...], out: str, layout: str | None) -> None:
    """Generate pydantic models from .proto files or a directory of them."""
    resolved_layout = layout or ("tree" if any(Path(p).is_dir() for p in protos) else "module")
    out_is_module = out.endswith(".py")
    if resolved_layout == "tree" and out_is_module:
        raise click.ClickException(
            "layout 'tree' writes a package directory, but -o ends with .py; "
            "pass --layout module for a single module or point -o at a directory"
        )
    if resolved_layout == "module" and not out_is_module:
        raise click.ClickException(
            "layout 'module' writes a single .py file, but -o does not end with .py; "
            "pass --layout tree for a package tree or point -o at a .py file"
        )

    try:
        fdset = compile_fdset(protos=protos, includes=includes)
        if resolved_layout == "module":
            source = generate_source(fdset_bytes=fdset)
            out_path = Path(out)
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(source, encoding="utf-8")
            click.echo(f"wrote {out_path}")
        else:
            files = generate_tree(fdset_bytes=fdset)
            _write_tree(out_dir=Path(out), files=files)
            click.echo(f"wrote {len(files)} files under {out}")
    except (RuntimeError, NotImplementedError, ValueError, OSError) as exc:
        raise click.ClickException(str(exc)) from exc


def _write_tree(*, out_dir: Path, files: dict[str, str]) -> None:
    """Managed-clean, failure-atomic write: refuse to touch anything foreign,
    build the replacement in a staging dir, then swap — a failed write can
    never destroy the previous valid tree."""
    if out_dir.exists():
        foreign = _foreign_files(out_dir=out_dir)
        if foreign:
            raise click.ClickException(
                f"output directory {out_dir} contains files not generated by protodantic: "
                f"{', '.join(foreign)}; refusing to modify"
            )

    staging = out_dir.parent / f"{out_dir.name}.protodantic-staging"
    backup = out_dir.parent / f"{out_dir.name}.protodantic-backup"
    for leftover in (staging, backup):
        if leftover.exists():
            shutil.rmtree(leftover)
    try:
        for rel_path, source in sorted(files.items()):
            target = staging / rel_path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(source, encoding="utf-8")
    except BaseException:
        shutil.rmtree(staging, ignore_errors=True)
        raise

    if out_dir.exists():
        out_dir.rename(backup)
        try:
            staging.rename(out_dir)
        except BaseException:
            backup.rename(out_dir)
            shutil.rmtree(staging, ignore_errors=True)
            raise
        shutil.rmtree(backup)
    else:
        out_dir.parent.mkdir(parents=True, exist_ok=True)
        staging.rename(out_dir)


def _foreign_files(*, out_dir: Path) -> list[str]:
    foreign: list[str] = []
    for path in sorted(out_dir.rglob("*")):
        if path.is_dir():
            continue
        rel_parts = path.relative_to(out_dir).parts
        # bytecode caches are byproducts of our own generated modules; judge
        # relative to out_dir so a __pycache__ ANCESTOR can't blind the scan
        if "__pycache__" in rel_parts:
            continue
        rel = "/".join(rel_parts)
        if path.suffix != ".py":
            foreign.append(rel)
            continue
        with path.open(encoding="utf-8", errors="replace") as handle:
            first_line = handle.readline()
        if _GENERATED_MARKER not in first_line:
            foreign.append(rel)
    return foreign


if __name__ == "__main__":
    main()
