from __future__ import annotations

import shutil
from pathlib import Path

import click

from ._version import __version__
from .codegen import generate_source, generate_tree
from .compiler import compile_fdset

_GENERATED_MARKER = "Generated by protodantic"


@click.group(context_settings={"help_option_names": ["-h", "--help"]})
@click.version_option(__version__, prog_name="protodantic")
def main() -> None:
    """Bidirectional bridge between Protocol Buffers and pydantic models."""


@main.command()
@click.argument("protos", nargs=-1, required=True)
@click.option(
    "-I", "--include", "includes", multiple=True, metavar="DIR",
    help="Additional import search path (repeatable).",
)
@click.option(
    "-o", "--out", "out", required=True, metavar="PATH",
    help="Output: a .py module file, or a package directory for tree layout.",
)
@click.option(
    "--layout", type=click.Choice(["module", "tree"]), default=None,
    help="Override the input-shape default (files -> module, directory -> tree).",
)
def generate(protos: tuple[str, ...], includes: tuple[str, ...], out: str, layout: str | None) -> None:
    """Generate pydantic models from .proto files or a directory of them."""
    resolved_layout = layout or ("tree" if any(Path(p).is_dir() for p in protos) else "module")
    out_is_module = out.endswith(".py")
    if resolved_layout == "tree" and out_is_module:
        raise click.ClickException(
            "layout 'tree' writes a package directory, but -o ends with .py; "
            "pass --layout module for a single module or point -o at a directory"
        )
    if resolved_layout == "module" and not out_is_module:
        raise click.ClickException(
            "layout 'module' writes a single .py file, but -o does not end with .py; "
            "pass --layout tree for a package tree or point -o at a .py file"
        )

    try:
        fdset = compile_fdset(protos=protos, includes=includes)
        if resolved_layout == "module":
            source = generate_source(fdset_bytes=fdset)
            out_path = Path(out)
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(source, encoding="utf-8")
            click.echo(f"wrote {out_path}")
        else:
            files = generate_tree(fdset_bytes=fdset)
            _write_tree(out_dir=Path(out), files=files)
            click.echo(f"wrote {len(files)} files under {out}")
    except (RuntimeError, NotImplementedError, ValueError, OSError) as exc:
        raise click.ClickException(str(exc)) from exc


def _write_tree(*, out_dir: Path, files: dict[str, str]) -> None:
    """Managed-clean write: replace previously generated content wholesale so
    stale modules can't survive, but refuse to touch anything foreign."""
    if out_dir.exists():
        foreign = _foreign_files(out_dir=out_dir)
        if foreign:
            raise click.ClickException(
                f"output directory {out_dir} contains files not generated by protodantic: "
                f"{', '.join(foreign)}; refusing to modify"
            )
        shutil.rmtree(out_dir)
    for rel_path, source in sorted(files.items()):
        target = out_dir / rel_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(source, encoding="utf-8")


def _foreign_files(*, out_dir: Path) -> list[str]:
    foreign: list[str] = []
    for path in sorted(out_dir.rglob("*")):
        if path.is_dir() or "__pycache__" in path.parts:
            continue
        rel = path.relative_to(out_dir).as_posix()
        if path.suffix != ".py":
            foreign.append(rel)
            continue
        with path.open(encoding="utf-8", errors="replace") as handle:
            first_line = handle.readline()
        if _GENERATED_MARKER not in first_line:
            foreign.append(rel)
    return foreign


if __name__ == "__main__":
    main()
