"""Generate pydantic model source code from a serialized FileDescriptorSet."""

from __future__ import annotations

import base64
import textwrap
from collections import Counter

from google.protobuf import descriptor_pb2
from google.protobuf.descriptor import Descriptor, EnumDescriptor, FieldDescriptor, OneofDescriptor

from protodantic.runtime import load_pool, python_field_name

# proto scalar type -> (python annotation, default expression)
_SCALARS: dict[int, tuple[str, str]] = {
    FieldDescriptor.TYPE_DOUBLE: ("float", "0.0"),
    FieldDescriptor.TYPE_FLOAT: ("float", "0.0"),
    FieldDescriptor.TYPE_INT64: ("Int64", "0"),
    FieldDescriptor.TYPE_UINT64: ("UInt64", "0"),
    FieldDescriptor.TYPE_INT32: ("Int32", "0"),
    FieldDescriptor.TYPE_FIXED64: ("UInt64", "0"),
    FieldDescriptor.TYPE_FIXED32: ("UInt32", "0"),
    FieldDescriptor.TYPE_BOOL: ("bool", "False"),
    FieldDescriptor.TYPE_STRING: ("str", '""'),
    FieldDescriptor.TYPE_BYTES: ("bytes", 'b""'),
    FieldDescriptor.TYPE_UINT32: ("UInt32", "0"),
    FieldDescriptor.TYPE_SFIXED32: ("Int32", "0"),
    FieldDescriptor.TYPE_SFIXED64: ("Int64", "0"),
    FieldDescriptor.TYPE_SINT32: ("Int32", "0"),
    FieldDescriptor.TYPE_SINT64: ("Int64", "0"),
}

# well-known types handled by the runtime instead of generated classes
_WKT_PY: dict[str, str] = {
    "google.protobuf.Timestamp": "datetime.datetime",
    "google.protobuf.Duration": "datetime.timedelta",
    "google.protobuf.Any": "Any",
    "google.protobuf.Struct": "dict[str, Any]",
    "google.protobuf.Value": "Any",
    "google.protobuf.ListValue": "list[Any]",
    "google.protobuf.DoubleValue": "float",
    "google.protobuf.FloatValue": "float",
    "google.protobuf.Int64Value": "Int64",
    "google.protobuf.UInt64Value": "UInt64",
    "google.protobuf.Int32Value": "Int32",
    "google.protobuf.UInt32Value": "UInt32",
    "google.protobuf.BoolValue": "bool",
    "google.protobuf.StringValue": "str",
    "google.protobuf.BytesValue": "bytes",
}

_HEADER = '''\
"""Generated by protodantic. DO NOT EDIT."""

from __future__ import annotations

import base64
import datetime
from typing import Any, ClassVar

from pydantic import Field

from protodantic.runtime import OpenEnum, ProtoModel, load_pool
from protodantic.types import Int32, Int64, UInt32, UInt64

'''


def _is_synthetic_oneof(oneof: OneofDescriptor) -> bool:
    """proto3 `optional` fields are backed by single-field synthetic oneofs
    named `_<field>`; those are presence plumbing, not user-facing groups."""
    fields = list(oneof.fields)
    return len(fields) == 1 and oneof.name == "_" + fields[0].name


def generate_source(fdset_bytes: bytes) -> str:
    """Render one python module with models for every message in the set.

    Files under google/protobuf/ are treated as runtime-provided (Timestamp,
    Duration, Any, Struct, wrappers...) and get no generated classes.
    """
    fdset = descriptor_pb2.FileDescriptorSet.FromString(fdset_bytes)

    for file_proto in fdset.file:
        if file_proto.name.startswith("google/protobuf/"):
            continue
        if file_proto.syntax != "proto3":
            raise NotImplementedError(
                f"{file_proto.name}: protodantic supports proto3 only, "
                f"got {file_proto.syntax or 'proto2'}"
            )

    pool = load_pool(fdset_bytes)

    # (kind, descriptor, base python name, package) in emission order
    entries: list[tuple[str, Descriptor | EnumDescriptor, str, str]] = []

    def register_message(desc: Descriptor, prefix: str, package: str) -> None:
        if desc.GetOptions().map_entry:
            return
        base = prefix + desc.name
        entries.append(("message", desc, base, package))
        for enum_desc in desc.enum_types:
            entries.append(("enum", enum_desc, f"{base}_{enum_desc.name}", package))
        for nested in desc.nested_types:
            register_message(nested, base + "_", package)

    for file_proto in fdset.file:
        if file_proto.name.startswith("google/protobuf/"):
            continue
        file_desc = pool.FindFileByName(file_proto.name)
        for enum_desc in file_desc.enum_types_by_name.values():
            entries.append(("enum", enum_desc, enum_desc.name, file_desc.package))
        for msg_desc in file_desc.message_types_by_name.values():
            register_message(msg_desc, "", file_desc.package)

    # Same base name in two packages -> qualify with the package path.
    base_counts = Counter(base for _, _, base, _ in entries)
    py_names: dict[str, str] = {}
    for _, desc, base, package in entries:
        if base_counts[base] > 1 and package:
            py_names[desc.full_name] = f"{package.replace('.', '_')}_{base}"
        else:
            py_names[desc.full_name] = base

    def base_type(fd: FieldDescriptor) -> str:
        if fd.type == FieldDescriptor.TYPE_MESSAGE:
            full_name = fd.message_type.full_name
            if full_name in _WKT_PY:
                return _WKT_PY[full_name]
            return py_names[full_name]
        if fd.type == FieldDescriptor.TYPE_ENUM:
            return py_names[fd.enum_type.full_name]
        return _SCALARS[fd.type][0]

    def annotation(fd: FieldDescriptor) -> str:
        if fd.type == FieldDescriptor.TYPE_MESSAGE and fd.message_type.GetOptions().map_entry:
            key_fd = fd.message_type.fields_by_name["key"]
            value_fd = fd.message_type.fields_by_name["value"]
            return f"dict[{base_type(key_fd)}, {base_type(value_fd)}]"
        if fd.is_repeated:
            return f"list[{base_type(fd)}]"
        if fd.has_presence:
            return f"{base_type(fd)} | None"
        return base_type(fd)

    def default(fd: FieldDescriptor) -> str:
        """Default expression; aliased fields need Field(...) to carry the alias."""
        alias = f'"{fd.name}"' if python_field_name(fd.name) != fd.name else None
        if fd.type == FieldDescriptor.TYPE_MESSAGE and fd.message_type.GetOptions().map_entry:
            factory = "Field(default_factory=dict"
            return f'{factory}, alias={alias})' if alias else factory + ")"
        if fd.is_repeated:
            factory = "Field(default_factory=list"
            return f'{factory}, alias={alias})' if alias else factory + ")"
        if fd.has_presence:
            plain = "None"
        elif fd.type == FieldDescriptor.TYPE_ENUM:
            plain = f"{py_names[fd.enum_type.full_name]}(0)"
        else:
            plain = _SCALARS[fd.type][1]
        if alias:
            return f"Field(default={plain}, alias={alias})"
        return plain

    parts: list[str] = [_HEADER]

    encoded = base64.b64encode(fdset_bytes).decode("ascii")
    chunks = "\n".join(f'    "{line}"' for line in textwrap.wrap(encoded, 84))
    parts.append(f"_POOL = load_pool(base64.b64decode(\n{chunks}\n))\n")

    for kind, desc, _, _ in entries:
        if kind != "enum":
            continue
        lines = [f"class {py_names[desc.full_name]}(OpenEnum):"]
        for value in desc.values:
            lines.append(f"    {value.name} = {value.number}")
        parts.append("\n".join(lines) + "\n")

    message_names: list[str] = []
    for kind, desc, _, _ in entries:
        if kind != "message":
            continue
        py_name = py_names[desc.full_name]
        message_names.append(py_name)
        lines = [
            f"class {py_name}(ProtoModel):",
            f'    __proto_full_name__: ClassVar[str] = "{desc.full_name}"',
            "    __proto_pool__: ClassVar[Any] = _POOL",
        ]
        real_oneofs = [o for o in desc.oneofs if not _is_synthetic_oneof(o)]
        if real_oneofs:
            groups = ", ".join(
                '"{}": ({})'.format(
                    oneof.name,
                    ", ".join(f'"{python_field_name(f.name)}"' for f in oneof.fields)
                    + ("," if len(oneof.fields) == 1 else ""),
                )
                for oneof in real_oneofs
            )
            lines.append(
                f"    __proto_oneofs__: ClassVar[dict[str, tuple[str, ...]]] = {{{groups}}}"
            )
        if desc.fields:
            lines.append("")
        for fd in desc.fields:
            lines.append(f"    {python_field_name(fd.name)}: {annotation(fd)} = {default(fd)}")
        parts.append("\n".join(lines) + "\n")

    if message_names:
        names = ", ".join(message_names)
        trailing = "," if len(message_names) == 1 else ""
        parts.append(f"for _model in ({names}{trailing}):\n    _model.model_rebuild()\ndel _model\n")

    return "\n\n".join(parts)
