from __future__ import annotations

import base64
import keyword
import string
import textwrap
from collections import Counter
from typing import NamedTuple

from google.protobuf import (
    any_pb2,
    descriptor_pb2,
    duration_pb2,
    struct_pb2,
    timestamp_pb2,
    wrappers_pb2,
)
from google.protobuf.descriptor import (
    Descriptor,
    EnumDescriptor,
    FieldDescriptor,
    FileDescriptor,
    OneofDescriptor,
)

from ._version import __version__
from .runtime import load_pool, python_field_name

# proto scalar type -> (python annotation, default expression); protodantic
# names go through the _pd module alias so user message names can never
# shadow them inside the generated module
_SCALARS: dict[int, tuple[str, str]] = {
    FieldDescriptor.TYPE_DOUBLE: ("float", "0.0"),
    FieldDescriptor.TYPE_FLOAT: ("float", "0.0"),
    FieldDescriptor.TYPE_INT64: ("_pd.Int64", "0"),
    FieldDescriptor.TYPE_UINT64: ("_pd.UInt64", "0"),
    FieldDescriptor.TYPE_INT32: ("_pd.Int32", "0"),
    FieldDescriptor.TYPE_FIXED64: ("_pd.UInt64", "0"),
    FieldDescriptor.TYPE_FIXED32: ("_pd.UInt32", "0"),
    FieldDescriptor.TYPE_BOOL: ("bool", "False"),
    FieldDescriptor.TYPE_STRING: ("str", '""'),
    FieldDescriptor.TYPE_BYTES: ("bytes", 'b""'),
    FieldDescriptor.TYPE_UINT32: ("_pd.UInt32", "0"),
    FieldDescriptor.TYPE_SFIXED32: ("_pd.Int32", "0"),
    FieldDescriptor.TYPE_SFIXED64: ("_pd.Int64", "0"),
    FieldDescriptor.TYPE_SINT32: ("_pd.Int32", "0"),
    FieldDescriptor.TYPE_SINT64: ("_pd.Int64", "0"),
}

# well-known types are handled by the runtime, not generated as classes; all
# imported names in generated code are underscore-aliased so user message
# names (e.g. `message Any`) can never shadow them
_WKT_PY: dict[str, str] = {
    timestamp_pb2.Timestamp.DESCRIPTOR.full_name: "_datetime.datetime",
    duration_pb2.Duration.DESCRIPTOR.full_name: "_datetime.timedelta",
    any_pb2.Any.DESCRIPTOR.full_name: "_typing.Any",
    struct_pb2.Struct.DESCRIPTOR.full_name: "_pd.Struct",
    struct_pb2.Value.DESCRIPTOR.full_name: "_pd.Value",
    struct_pb2.ListValue.DESCRIPTOR.full_name: "_pd.ListValue",
    wrappers_pb2.DoubleValue.DESCRIPTOR.full_name: "float",
    wrappers_pb2.FloatValue.DESCRIPTOR.full_name: "float",
    wrappers_pb2.Int64Value.DESCRIPTOR.full_name: "_pd.Int64",
    wrappers_pb2.UInt64Value.DESCRIPTOR.full_name: "_pd.UInt64",
    wrappers_pb2.Int32Value.DESCRIPTOR.full_name: "_pd.Int32",
    wrappers_pb2.UInt32Value.DESCRIPTOR.full_name: "_pd.UInt32",
    wrappers_pb2.BoolValue.DESCRIPTOR.full_name: "bool",
    wrappers_pb2.StringValue.DESCRIPTOR.full_name: "str",
    wrappers_pb2.BytesValue.DESCRIPTOR.full_name: "bytes",
}

# single source of truth for our output header; the managed-clean regeneration
# scan in cli.py validates the complete shape via _is_generated_header so a
# handwritten line merely mentioning the marker is never mistaken for ours
_GENERATED_STAMP_PREFIX = '"""Generated by protodantic '
_GENERATED_STAMP_SUFFIX = '. DO NOT EDIT."""'
_GENERATED_STAMP = f"{_GENERATED_STAMP_PREFIX}{__version__}{_GENERATED_STAMP_SUFFIX}"


def _is_generated_header(*, line: str) -> bool:
    stripped = line.rstrip("\r\n")
    return stripped.startswith(_GENERATED_STAMP_PREFIX) and stripped.endswith(
        _GENERATED_STAMP_SUFFIX
    )


# files whose types the runtime converts natively (plus descriptor.proto:
# proto2 compile-time metadata that custom-options schemas import); everything
# else in the fdset gets generated models — including user files that happen
# to live under google/protobuf/
_RUNTIME_HANDLED_DESCRIPTORS = {
    m.DESCRIPTOR.name: m.DESCRIPTOR
    for m in (any_pb2, descriptor_pb2, duration_pb2, struct_pb2, timestamp_pb2, wrappers_pb2)
}
_RUNTIME_HANDLED_FILES = frozenset(_RUNTIME_HANDLED_DESCRIPTORS)

_HEADER = f"""\
{_GENERATED_STAMP}

from __future__ import annotations

import base64 as _base64
import datetime as _datetime
import typing as _typing

from pydantic import Field as _Field

import protodantic as _pd

"""

_INIT_SOURCE = _GENERATED_STAMP + "\n"

_B64_LINE_WIDTH = 84

# names a generated type may not use: builtins that appear in generated
# annotations/defaults, and the names the generated module itself emits
_REFERENCED_BUILTINS = frozenset({"bool", "bytes", "dict", "float", "int", "list", "str", "tuple"})
_EMITTED_MODULE_NAMES = frozenset(
    {"_pd", "_typing", "_datetime", "_base64", "_Field", "_POOL", "_pdesc", "_model"}
)
# names the enum machinery reserves on members
_RESERVED_ENUM_MEMBERS = frozenset({"mro"})

_IDENTIFIER_CHARS = frozenset(string.ascii_letters + string.digits + "_")
# module stems reserved for protodantic's own emitted files / python tooling
_RESERVED_STEMS = frozenset({"__init__", "_descriptors", "__pycache__"})


class _Entry(NamedTuple):
    kind: str  # "message" | "enum"
    desc: Descriptor | EnumDescriptor
    base_name: str
    package: str


def generate_source(fdset_bytes: bytes, *, proto2: str = "error") -> str:
    """Render one python module with pydantic models for every message in the
    serialized FileDescriptorSet. proto2="skip" generates only the proto3
    subset of a mixed-syntax set (proto3->proto2 references fail loudly)."""
    return _ModuleGenerator(fdset_bytes=fdset_bytes, proto2=proto2).render()


def generate_tree(fdset_bytes: bytes, *, proto2: str = "error") -> dict[str, str]:
    """Render a python package tree (one module per proto file, mirroring the
    proto file paths) for every message in the serialized FileDescriptorSet.
    Returns a mapping of posix-relative module paths to source text. proto2
    behaves as in generate_source."""
    return _TreeGenerator(fdset_bytes=fdset_bytes, proto2=proto2).render()


def _is_runtime_handled_file(*, file_name: str) -> bool:
    return file_name in _RUNTIME_HANDLED_FILES


def _is_synthetic_oneof(*, oneof: OneofDescriptor) -> bool:
    # proto3 `optional` is backed by a single-field oneof named _<field>
    fields = list(oneof.fields)
    return len(fields) == 1 and oneof.name == "_" + fields[0].name


def _is_map_field(*, fd: FieldDescriptor) -> bool:
    return fd.type == FieldDescriptor.TYPE_MESSAGE and fd.message_type.GetOptions().map_entry


def _python_type_name(*, name: str) -> str:
    """Trailing-underscore escape (same rule as fields) for type names that
    are python keywords or would shadow names the generated module relies on."""
    if keyword.iskeyword(name) or name in _REFERENCED_BUILTINS or name in _EMITTED_MODULE_NAMES:
        return name + "_"
    return name


def _python_enum_member(*, name: str) -> str:
    if keyword.iskeyword(name) or name in _RESERVED_ENUM_MEMBERS:
        return name + "_"
    return name


def _sanitize_path_segment(*, segment: str) -> str:
    """Module-path normalization, a pure function of the segment: characters
    outside [A-Za-z0-9_] become _ (1:1, no collapsing), a leading digit gains
    a _ prefix, keywords and reserved stems get the trailing-underscore escape."""
    cleaned = "".join(ch if ch in _IDENTIFIER_CHARS else "_" for ch in segment) or "_"
    if cleaned[0].isdigit():
        cleaned = "_" + cleaned
    if keyword.iskeyword(cleaned) or cleaned in _RESERVED_STEMS:
        cleaned += "_"
    return cleaned


def _dep_alias(*, segments: tuple[str, ...]) -> str:
    # length-prefixed segments make the encoding injective: plain joining
    # would collide for e.g. ("a", "b__c") vs ("a__b", "c"); segments never
    # start with a digit, so the length prefix is unambiguous
    return "_dep_" + "_".join(f"{len(segment)}{segment}" for segment in segments)


def _reject_shadowed_runtime_files(*, fdset: descriptor_pb2.FileDescriptorSet) -> None:
    """Reject reserved runtime-handled files that differ from the shipped schema."""
    for file_proto in fdset.file:
        shipped = _RUNTIME_HANDLED_DESCRIPTORS.get(file_proto.name)
        if shipped is None:
            continue
        expected = descriptor_pb2.FileDescriptorProto()
        shipped.CopyToProto(expected)
        if _normalized_descriptor_bytes(file_proto=file_proto) != _normalized_descriptor_bytes(
            file_proto=expected
        ):
            raise ValueError(
                f"{file_proto.name} does not match the protobuf runtime's file of the same "
                "name; protodantic maps these types to runtime equivalents, so a diverging "
                "copy would generate silently wrong models. Rename the file."
            )


def _normalized_descriptor_bytes(*, file_proto: descriptor_pb2.FileDescriptorProto) -> bytes:
    normalized = descriptor_pb2.FileDescriptorProto()
    normalized.CopyFrom(file_proto)
    # Source locations do not affect schema semantics and may be absent from
    # reflected descriptors.
    normalized.ClearField("source_code_info")
    return normalized.SerializeToString(deterministic=True)


def _resolve_proto2_files(
    *, fdset: descriptor_pb2.FileDescriptorSet, proto2: str
) -> frozenset[str]:
    """Names of files to skip under proto2="skip"; under the default "error"
    mode any non-proto3 file raises as before."""
    if proto2 not in ("error", "skip"):
        raise ValueError(f"proto2 mode must be 'error' or 'skip', got {proto2!r}")
    schema_files = [f for f in fdset.file if not _is_runtime_handled_file(file_name=f.name)]
    non_proto3 = [f for f in schema_files if f.syntax != "proto3"]
    if not non_proto3:
        return frozenset()
    # the skip flag is proto2-specific: editions (or anything newer) must
    # error in BOTH modes, never be skipped under a mislabeled audit trail
    unsupported = [f for f in non_proto3 if f.syntax not in ("", "proto2")]
    if unsupported:
        first = unsupported[0]
        raise NotImplementedError(
            f"{first.name}: protodantic supports proto3 only, got {first.syntax}"
        )
    if proto2 == "error":
        first = non_proto3[0]
        count_note = f" ({len(non_proto3)} proto2 files total)" if len(non_proto3) > 1 else ""
        # only advertise the flag when a proto3 subset exists to generate —
        # on an all-proto2 input the advice would immediately fail
        hint = (
            ' (pass proto2="skip" / --proto2 skip to generate only the proto3 files)'
            if len(non_proto3) < len(schema_files)
            else ""
        )
        raise NotImplementedError(
            f"{first.name}: protodantic supports proto3 only, "
            f"got {first.syntax or 'proto2'}{count_note}{hint}"
        )
    if len(non_proto3) == len(schema_files):
        raise ValueError(
            'every schema file is proto2; there are no proto3 files to generate with proto2="skip"'
        )
    return frozenset(f.name for f in non_proto3)


def _reject_proto2_bridges(*, entries: list[_Entry], skipped_files: frozenset[str]) -> None:
    """proto3 fields embedding types from skipped proto2 files make the proto3
    subset non-generatable on its own — name every coupling point. (protoc
    already forbids proto3 fields of proto2 enum types, so message embeds are
    the only crossable reference.)"""
    bridges = []
    for entry in entries:
        if entry.kind != "message":
            continue
        for fd in entry.desc.fields:
            for type_desc in _field_type_descriptors(fd=fd):
                if type_desc.file.name in skipped_files:
                    bridges.append(
                        f"{entry.desc.full_name}.{fd.name} -> {type_desc.full_name} "
                        f"({type_desc.file.name})"
                    )
    if bridges:
        raise ValueError(
            "proto3 fields reference types from skipped proto2 files: "
            + "; ".join(sorted(bridges))
            + ". The proto3 subset cannot be generated standalone; migrate these "
            "types to proto3 or generate without skipping."
        )


def _render_skipped_comment(*, skipped_files: frozenset[str]) -> str:
    return '# proto2 files skipped (proto2="skip"): ' + ", ".join(sorted(skipped_files))


def _collect_file_entries(*, file_desc: FileDescriptor) -> list[_Entry]:
    entries: list[_Entry] = []
    for enum_desc in file_desc.enum_types_by_name.values():
        entries.append(
            _Entry(kind="enum", desc=enum_desc, base_name=enum_desc.name, package=file_desc.package)
        )
    for msg_desc in file_desc.message_types_by_name.values():
        _collect_message_entries(
            desc=msg_desc, prefix="", package=file_desc.package, entries=entries
        )
    return entries


def _collect_message_entries(
    *, desc: Descriptor, prefix: str, package: str, entries: list[_Entry]
) -> None:
    if desc.GetOptions().map_entry:
        return
    base_name = prefix + desc.name
    entries.append(_Entry(kind="message", desc=desc, base_name=base_name, package=package))
    for enum_desc in desc.enum_types:
        entries.append(
            _Entry(
                kind="enum",
                desc=enum_desc,
                base_name=f"{base_name}_{enum_desc.name}",
                package=package,
            )
        )
    for nested in desc.nested_types:
        _collect_message_entries(
            desc=nested, prefix=base_name + "_", package=package, entries=entries
        )


def _assign_python_names(*, entries: list[_Entry], qualify_packages: bool) -> dict[str, str]:
    """Python class names for entries; when qualify_packages is set, same base
    name in two packages gets the package path prefixed."""
    base_counts = Counter(entry.base_name for entry in entries)
    py_names: dict[str, str] = {}
    for entry in entries:
        if qualify_packages and base_counts[entry.base_name] > 1 and entry.package:
            name = f"{entry.package.replace('.', '_')}_{entry.base_name}"
        else:
            name = entry.base_name
        py_names[entry.desc.full_name] = _python_type_name(name=name)
    _reject_residual_collisions(py_names=py_names)
    return py_names


def _reject_residual_collisions(*, py_names: dict[str, str]) -> None:
    # flattening joins nesting with "_", so Outer.Inner and a literal
    # Outer_Inner collide even within one package — refuse, never overwrite
    by_python_name: dict[str, list[str]] = {}
    for full_name, py_name in py_names.items():
        by_python_name.setdefault(py_name, []).append(full_name)
    collisions = {name: fulls for name, fulls in by_python_name.items() if len(fulls) > 1}
    if collisions:
        details = "; ".join(
            f"{' and '.join(sorted(fulls))} both map to {name!r}"
            for name, fulls in sorted(collisions.items())
        )
        raise ValueError(
            f"python class name collision after flattening: {details}. "
            "Rename one of the conflicting proto types."
        )


def _field_type_descriptors(*, fd: FieldDescriptor) -> list[Descriptor | EnumDescriptor]:
    """Descriptors a field's annotation refers to (map entries dug through;
    runtime-handled well-known types excluded)."""
    if _is_map_field(fd=fd):
        refs: list[Descriptor | EnumDescriptor] = []
        for sub in (fd.message_type.fields_by_name["key"], fd.message_type.fields_by_name["value"]):
            refs.extend(_field_type_descriptors(fd=sub))
        return refs
    if fd.type == FieldDescriptor.TYPE_MESSAGE:
        if fd.message_type.full_name in _WKT_PY:
            return []
        return [fd.message_type]
    if fd.type == FieldDescriptor.TYPE_ENUM:
        return [fd.enum_type]
    return []


class _BaseRenderer:
    """Shared enum/message rendering; concrete generators provide _entries
    (what to emit) and _py_names (how any full name is referenced here)."""

    _entries: list[_Entry]
    _py_names: dict[str, str]

    def _base_type(self, *, fd: FieldDescriptor) -> str:
        if fd.type == FieldDescriptor.TYPE_MESSAGE:
            full_name = fd.message_type.full_name
            if full_name in _WKT_PY:
                return _WKT_PY[full_name]
            return self._py_names[full_name]
        if fd.type == FieldDescriptor.TYPE_ENUM:
            return self._py_names[fd.enum_type.full_name]
        return _SCALARS[fd.type][0]

    def _annotation(self, *, fd: FieldDescriptor) -> str:
        if _is_map_field(fd=fd):
            key_fd = fd.message_type.fields_by_name["key"]
            value_fd = fd.message_type.fields_by_name["value"]
            return f"dict[{self._base_type(fd=key_fd)}, {self._base_type(fd=value_fd)}]"
        if fd.is_repeated:
            return f"list[{self._base_type(fd=fd)}]"
        if fd.has_presence:
            return f"{self._base_type(fd=fd)} | None"
        return self._base_type(fd=fd)

    def _default(self, *, fd: FieldDescriptor) -> str:
        alias = f'"{fd.name}"' if python_field_name(proto_name=fd.name) != fd.name else None
        if _is_map_field(fd=fd):
            return (
                f"_Field(default_factory=dict, alias={alias})"
                if alias
                else "_Field(default_factory=dict)"
            )
        if fd.is_repeated:
            return (
                f"_Field(default_factory=list, alias={alias})"
                if alias
                else "_Field(default_factory=list)"
            )
        if fd.has_presence:
            plain = "None"
        elif fd.type == FieldDescriptor.TYPE_ENUM:
            plain = f"{self._py_names[fd.enum_type.full_name]}(0)"
        else:
            plain = _SCALARS[fd.type][1]
        return f"_Field(default={plain}, alias={alias})" if alias else plain

    def _render_enum(self, *, desc: EnumDescriptor) -> str:
        py_name = self._py_names[desc.full_name]
        members = [(_python_enum_member(name=v.name), v.name, v.number) for v in desc.values]
        self._reject_member_collisions(enum_name=desc.full_name, members=members)
        lines = [f"class {py_name}(_pd.OpenEnum):"]
        lines.extend(f"    {member} = {number}" for member, _, number in members)
        return "\n".join(lines) + "\n"

    def _reject_member_collisions(
        self, *, enum_name: str, members: list[tuple[str, str, int]]
    ) -> None:
        # escaping can map two proto member names to one python name; python
        # enums forbid redeclaring a name (even for same-value aliases), so
        # refuse rather than crash opaquely at import
        by_member: dict[str, list[str]] = {}
        for py_member, proto_member, _ in members:
            by_member.setdefault(py_member, []).append(proto_member)
        collisions = {py: names for py, names in by_member.items() if len(names) > 1}
        if collisions:
            details = "; ".join(
                f"{' and '.join(names)} both map to {py!r}"
                for py, names in sorted(collisions.items())
            )
            raise ValueError(
                f"enum {enum_name!r}: member name collision after escaping: {details}. "
                "Rename one of the conflicting members."
            )

    def _render_message(self, *, desc: Descriptor) -> str:
        lines = [
            f"class {self._py_names[desc.full_name]}(_pd.ProtoModel):",
            f'    __proto_full_name__: _typing.ClassVar[str] = "{desc.full_name}"',
            "    __proto_pool__: _typing.ClassVar[_typing.Any] = _POOL",
        ]
        oneofs = self._render_oneofs(desc=desc)
        if oneofs:
            lines.append(oneofs)
        if desc.fields:
            lines.append("")
        lines.extend(
            f"    {python_field_name(proto_name=fd.name)}: {self._annotation(fd=fd)} = {self._default(fd=fd)}"
            for fd in desc.fields
        )
        return "\n".join(lines) + "\n"

    def _render_oneofs(self, *, desc: Descriptor) -> str | None:
        real_oneofs = [o for o in desc.oneofs if not _is_synthetic_oneof(oneof=o)]
        if not real_oneofs:
            return None
        groups = ", ".join(
            '"{}": ({})'.format(
                oneof.name,
                ", ".join(f'"{python_field_name(proto_name=f.name)}"' for f in oneof.fields)
                + ("," if len(oneof.fields) == 1 else ""),
            )
            for oneof in real_oneofs
        )
        return f"    __proto_oneofs__: _typing.ClassVar[dict[str, tuple[str, ...]]] = {{{groups}}}"

    def _render_rebuild(self) -> str | None:
        names = [self._py_names[e.desc.full_name] for e in self._entries if e.kind == "message"]
        if not names:
            return None
        joined = ", ".join(names)
        trailing = "," if len(names) == 1 else ""
        return f"for _model in ({joined}{trailing}):\n    _model.model_rebuild()\ndel _model\n"

    def _render_body(self) -> list[str]:
        parts: list[str] = []
        parts.extend(self._render_enum(desc=e.desc) for e in self._entries if e.kind == "enum")
        parts.extend(
            self._render_message(desc=e.desc) for e in self._entries if e.kind == "message"
        )
        rebuild = self._render_rebuild()
        if rebuild:
            parts.append(rebuild)
        return parts


def _render_b64_chunks(*, data: bytes) -> str:
    encoded = base64.b64encode(data).decode("ascii")
    return "\n".join(f'    "{line}"' for line in textwrap.wrap(encoded, _B64_LINE_WIDTH))


class _ModuleGenerator(_BaseRenderer):
    """Single-module output: every message in the set, package-qualified on
    cross-package name collisions, descriptors embedded inline."""

    def __init__(self, *, fdset_bytes: bytes, proto2: str) -> None:
        self._fdset_bytes = fdset_bytes
        self._fdset = descriptor_pb2.FileDescriptorSet.FromString(fdset_bytes)
        self._pool = load_pool(fdset_bytes)
        self._proto2 = proto2
        self._entries = []
        self._py_names = {}

    def render(self) -> str:
        _reject_shadowed_runtime_files(fdset=self._fdset)
        skipped = _resolve_proto2_files(fdset=self._fdset, proto2=self._proto2)
        for file_proto in self._fdset.file:
            if _is_runtime_handled_file(file_name=file_proto.name) or file_proto.name in skipped:
                continue
            file_desc = self._pool.FindFileByName(file_proto.name)
            self._entries.extend(_collect_file_entries(file_desc=file_desc))
        _reject_proto2_bridges(entries=self._entries, skipped_files=skipped)
        self._py_names = _assign_python_names(entries=self._entries, qualify_packages=True)

        pool_line = f"_POOL = _pd.load_pool(_base64.b64decode(\n{_render_b64_chunks(data=self._fdset_bytes)}\n))\n"
        parts = [_HEADER, pool_line]
        if skipped:
            parts.append(_render_skipped_comment(skipped_files=skipped) + "\n")
        parts.extend(self._render_body())
        return "\n\n".join(parts)


class _FileModuleRenderer(_BaseRenderer):
    """One proto file's module inside a generated tree."""

    def __init__(self, *, entries: list[_Entry], py_names: dict[str, str], header: str) -> None:
        self._entries = entries
        self._py_names = py_names
        self._header = header

    def render(self) -> str:
        return "\n\n".join([self._header, *self._render_body()])


class _TreeGenerator:
    """Package-tree output: one module per proto file, module paths derived
    from file paths (never proto packages), a single shared descriptor pool,
    and root-anchored relative imports so the tree is relocatable."""

    def __init__(self, *, fdset_bytes: bytes, proto2: str) -> None:
        self._fdset_bytes = fdset_bytes
        self._fdset = descriptor_pb2.FileDescriptorSet.FromString(fdset_bytes)
        self._pool = load_pool(fdset_bytes)
        self._proto2 = proto2

    def render(self) -> dict[str, str]:
        _reject_shadowed_runtime_files(fdset=self._fdset)
        skipped = _resolve_proto2_files(fdset=self._fdset, proto2=self._proto2)
        file_names = [
            f.name
            for f in self._fdset.file
            if not _is_runtime_handled_file(file_name=f.name) and f.name not in skipped
        ]
        module_paths = _assign_module_paths(file_names=file_names)

        entries_by_file: dict[str, list[_Entry]] = {}
        local_names: dict[str, dict[str, str]] = {}
        for name in file_names:
            file_desc = self._pool.FindFileByName(name)
            entries = _collect_file_entries(file_desc=file_desc)
            entries_by_file[name] = entries
            local_names[name] = _assign_python_names(entries=entries, qualify_packages=False)
        _reject_proto2_bridges(
            entries=[entry for entries in entries_by_file.values() for entry in entries],
            skipped_files=skipped,
        )

        files: dict[str, str] = {
            "__init__.py": _INIT_SOURCE,
            "_descriptors.py": self._render_descriptors(skipped_files=skipped),
        }
        for segments in module_paths.values():
            for depth in range(1, len(segments)):
                files["/".join(segments[:depth]) + "/__init__.py"] = _INIT_SOURCE

        for name in file_names:
            segments = module_paths[name]
            dep_files = _referenced_files(entries=entries_by_file[name], current_file=name)
            py_names = dict(local_names[name])
            for dep_file in dep_files:
                alias = _dep_alias(segments=module_paths[dep_file])
                for full_name, local in local_names[dep_file].items():
                    py_names[full_name] = f"{alias}.{local}"
            header = _render_tree_module_header(
                depth=len(segments) - 1,
                dep_paths=sorted(module_paths[d] for d in dep_files),
            )
            renderer = _FileModuleRenderer(
                entries=entries_by_file[name], py_names=py_names, header=header
            )
            files["/".join(segments) + ".py"] = renderer.render()
        return files

    def _render_descriptors(self, *, skipped_files: frozenset[str]) -> str:
        audit = ""
        if skipped_files:
            audit = _render_skipped_comment(skipped_files=skipped_files) + "\n\n"
        return (
            _GENERATED_STAMP + "\n"
            "\n" + audit + "import base64 as _base64\n"
            "\n"
            "import protodantic as _pd\n"
            "\n"
            f"POOL = _pd.load_pool(_base64.b64decode(\n{_render_b64_chunks(data=self._fdset_bytes)}\n))\n"
        )


def _assign_module_paths(*, file_names: list[str]) -> dict[str, tuple[str, ...]]:
    result: dict[str, tuple[str, ...]] = {}
    raw_segments: dict[str, tuple[str, ...]] = {}
    owners: dict[tuple[str, ...], str] = {}
    for name in sorted(file_names):
        stem = name[: -len(".proto")] if name.endswith(".proto") else name
        raw = tuple(stem.split("/"))
        segments = tuple(_sanitize_path_segment(segment=s) for s in raw)
        if segments in owners:
            raise ValueError(
                f"module path collision: {owners[segments]!r} and {name!r} both map to "
                f"{'/'.join(segments)}.py. Rename one of the files."
            )
        owners[segments] = name
        result[name] = segments
        raw_segments[name] = raw

    # two distinct SOURCE directories normalizing to one python package is a
    # collision (silent merges would lie about the proto layout)
    dir_sources: dict[tuple[str, ...], str] = {}
    for name in sorted(result):
        segments, raw = result[name], raw_segments[name]
        for depth in range(1, len(segments)):
            key = segments[:depth]
            original = "/".join(raw[:depth])
            existing = dir_sources.setdefault(key, original)
            if existing != original:
                raise ValueError(
                    f"module path collision: source directories {existing!r} and {original!r} "
                    f"both normalize to python package {'/'.join(key)}/. Rename one of the directories."
                )

    dir_owners: dict[tuple[str, ...], str] = {}
    for name, segments in result.items():
        for depth in range(1, len(segments)):
            dir_owners.setdefault(segments[:depth], name)
    for name, segments in sorted(result.items()):
        if segments in dir_owners:
            raise ValueError(
                f"module path collision: {name!r} maps to module {'/'.join(segments)}.py but "
                f"{dir_owners[segments]!r} needs package directory {'/'.join(segments)}/. "
                "Rename one of the files."
            )
    return result


def _referenced_files(*, entries: list[_Entry], current_file: str) -> list[str]:
    refs: set[str] = set()
    for entry in entries:
        if entry.kind != "message":
            continue
        for fd in entry.desc.fields:
            for type_desc in _field_type_descriptors(fd=fd):
                declaring = type_desc.file.name
                if declaring != current_file and not _is_runtime_handled_file(file_name=declaring):
                    refs.add(declaring)
    return sorted(refs)


def _render_tree_module_header(*, depth: int, dep_paths: list[tuple[str, ...]]) -> str:
    dots = "." * (depth + 1)
    lines = [
        _GENERATED_STAMP,
        "",
        "from __future__ import annotations",
        "",
        "import datetime as _datetime",
        "import typing as _typing",
        "",
        "from pydantic import Field as _Field",
        "",
        "import protodantic as _pd",
        "",
        f"from {dots} import _descriptors as _pdesc",
    ]
    for target in dep_paths:
        alias = _dep_alias(segments=target)
        package_part = ".".join(target[:-1])
        lines.append(f"from {dots}{package_part} import {target[-1]} as {alias}")
    lines.extend(["", "_POOL = _pdesc.POOL", ""])
    return "\n".join(lines)
